### ISSUE TITLE
Incorporate doctrine/dbal patch for PHP 8.2 in TYPO3 v11 packaging

### ISSUE THREAD

**Issue by ohader** [TYPO3/darth#27]
* https://github.com/typo3/typo3/commit/dc0ad26929#diff-14b57c573d125eed1aed6e3b2adcc5808975f102f2b90b6615af264cbfa78cb5
* https://typo3.org/article/announcing-official-php-82-support-for-current-typo3-versions#postgresql-caveats
  > Our bundled versions (the tar.gz and zip files) include a patched version of Doctrine DBAL that fixes the underlying issue.

**Comment by bmack** [comment]
In the package command, we need to manually check for v11 versions, then call `new Process([patch, 'working/Build/...]) after the composer install.
